apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mysqlUser }}
  database-user:  {{ .Values.mysqlUser | b64enc | quote }}
  {{ else }}
  database-user: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysqlPassword }}
  database-password:  {{ .Values.mysqlPassword | b64enc | quote }}
  {{ else }}
  database-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysqlRootPassword }}
  database-root-password:  {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  database-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  database-name:  {{ default "sampledb" .Values.mysqlDatabase | b64enc | quote }}
 
